### ISSUE TITLE
atom_apm resource don't install packages

### ISSUE THREAD

**Issue by nicutor** [sous-chefs/atom#14]
Hi,

I am using:

default['atom']['packages'] = %w(language-chef linter-chefstyle)
node['atom']['packages'].each do |pkg|
  atom_apm "#{pkg}"
end

and the result is this:

  * atom_apm[language-chef] action install (up to date)
  * atom_apm[linter-chefstyle] action install (up to date)

But, it seems the packages are not installed at all.

* Windows 7 SP1 with latest updates
* chefdk 2.0.28
* PowerShell 5.1
* Microsoft Visual C++ 2010 x64 and x86

**Comment by MarkGibbons** [comment]
I'll see if this is fixed by the custom resource rewrite.

**Comment by MarkGibbons** [comment]
Windows 7 is no longer supported.
The new resource works in windows 2016.
Tested in version 0.3.00.
