### ISSUE TITLE
Changelog does not pass markdownlint

### ISSUE THREAD

**Issue by Xorima** [sous-chefs/atom#36]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

The changelog (and likely other .md files) do not pass markdown lint, these files should be brought in line with markdownlint in order for the CI/CD pipeline to work

## :pancakes: Cookbook version

Master

## Steps To Reproduce

Install markdownlint
run markdown lint
see failures

## :police_car: Expected behavior

markdown lint passes

**Comment by maskott** [comment]
I'd like to give it a shot ✋
