### ISSUE TITLE
Chef 17 deprecation warnings

### ISSUE THREAD

**Issue by MarkGibbons** [sous-chefs/atom#69]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

Chef 17 compatibility, change the default branch to main

## :heavy_plus_sign: Additional context

Add any other context about the problem here. e.g. related issues or existing pull requests.

**Comment by damacus** [comment]
Relates to #70

**Comment by MarkGibbons** [comment]
Duplicate
